version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile-mysql
    ports:
      - 3306:3306