version: '3.8'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 9000:8000
        depends_on: 
            - db

    queue:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        depends_on: 
            - db        

    db:
        build:
            context: ./mysql
            dockerfile: Dockerfile-mysql
        image: arm64v8/mysql:8.0
        environment:
            MYSQL_DATABASE: main
            MYSQL_USER: admin
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: admin
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
