FROM arm64v8/mysql:8.0

# Set environment variables for the database
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword
ENV MYSQL_ROOT_PASSWORD=myrootpassword

# Copy the initialization script to create the database and user
COPY init.sql /docker-entrypoint-initdb.d/

# Set the timezone
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime

# Change the ownership of the MySQL data directory to the MySQL user
RUN chown -R mysql:mysql /var/lib/mysql && \
    chmod -R 777 /var/lib/mysql

# Expose port 3306 for MySQL
EXPOSE 3306
